vars:
  - ROOT: ..
  - SRC: ../src/
stages:
  get-data:
    cmd: python get-data.py
    always_changed: true
    deps:
      - get-data.py
    outs:
      - ${ROOT}/raw/arts-council-investment-programme.csv:
          persist: true
          cache: false
      - ${ROOT}/raw/arts-council-project-grants.csv:
          persist: true
          cache: false
      - ${ROOT}/raw/company-data.zip:
          persist: true
          cache: false
      - ${ROOT}/raw/charity-data.zip:
          persist: true
          cache: false
      - ${ROOT}/raw/charity-area-data.zip:
          persist: true
          cache: false
      - ${ROOT}/raw/360-giving.csv:
          persist: true
          cache: false
      - ${ROOT}/raw/onspd.zip:
          persist: true
          cache: false

  prepare-geo:
    cmd: jupyter execute prepare-geo.ipynb
    deps:
      - prepare-geo.ipynb
      - ${ROOT}/raw/onspd.zip
    outs:
      - ${ROOT}/data/reference/onspd_extract.csv:
          persist: false
          cache: false

  geo:
    cmd: jupyter execute geo.ipynb
    deps:
      - geo.ipynb
    outs:
      - ${ROOT}/src/_data/geojson/lad/all.geojson:
          persist: false
          cache: false
      - ${ROOT}/src/_data/geojson/lad/E06000047.geojson:
          persist: false
          cache: false
      - ${ROOT}/src/_data/geojson/lad/E06000057.geojson:
          persist: false
          cache: false
      - ${ROOT}/src/_data/geojson/lad/E08000021.geojson:
          persist: false
          cache: false
      - ${ROOT}/src/_data/geojson/lad/E08000022.geojson:
          persist: false
          cache: false
      - ${ROOT}/src/_data/geojson/lad/E08000023.geojson:
          persist: false
          cache: false
      - ${ROOT}/src/_data/geojson/lad/E08000024.geojson:
          persist: false
          cache: false
      - ${ROOT}/src/_data/geojson/lad/E08000037.geojson:
          persist: false
          cache: false

  load-data:
    cmd: jupyter execute load-data.ipynb
    deps:
      - load-data.ipynb
      - ${ROOT}/raw/company-data.zip
      - ${ROOT}/raw/charity-data.zip
      - ${ROOT}/raw/charity-area-data.zip
    outs:
      - ${ROOT}/raw/company-data.db:
          persist: true
          cache: false

  arts-council:
    cmd: |
      papermill arts-council.ipynb - | jupyter nbconvert --stdin --to markdown --output index --output-dir ${SRC}/pipelines/arts-council
    deps:
      - arts-council.ipynb
      - ${ROOT}/raw/arts-council-investment-programme.csv
      - ${ROOT}/raw/arts-council-project-grants.csv
    outs:
      - ${SRC}/data/arts-council/investment-programme/_data/funding_by_organisation.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/investment-programme/_data/investment_by_lad.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/project-grants/_data/grants_by_recipient.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/project-grants/_data/grants_value_by_lad_by_year.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/project-grants/_data/grants_count_by_lad_by_year.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/project-grants/_data/grants_average_award_by_lad_by_year.csv:
          persist: true
          cache: false
