vars:
  - ROOT: ..
  - SRC: ../src/
stages:
  get-data:
    cmd: python get-data.py
    always_changed: true
    deps:
      - get-data.py
    outs:
      - ${ROOT}/raw/arts-council-investment-programme.csv:
          persist: true
          cache: false
      - ${ROOT}/raw/arts-council-project-grants.csv:
          persist: true
          cache: false
      - ${ROOT}/raw/company-data.zip:
          persist: true
          cache: false

  load-data:
    cmd: papermill load-data.ipynb - | jupyter nbconvert --stdin --stdout --to markdown
    deps:
      - load-data.ipynb
      - ${ROOT}/raw/company-data.zip
      - ${ROOT}/raw/charity-data.zip
      - ${ROOT}/raw/charity-area-data.zip
    outs:
      - ${ROOT}/raw/company-data.db:
          persist: true
          cache: false

  arts-council:
    cmd: |
      papermill arts-council.ipynb - | jupyter nbconvert --stdin --to markdown --output index --output-dir ${SRC}/pipelines/arts-council
    deps:
      - arts-council.ipynb
      - ${ROOT}/raw/arts-council-investment-programme.csv
      - ${ROOT}/raw/arts-council-project-grants.csv
    outs:
      - ${SRC}/data/arts-council/investment-programme/_data/funding_by_organisation.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/investment-programme/_data/investment_by_lad.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/project-grants/_data/grants_by_recipient.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/project-grants/_data/grants_value_by_lad_by_year.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/project-grants/_data/grants_count_by_lad_by_year.csv:
          persist: true
          cache: false
      - ${SRC}/data/arts-council/project-grants/_data/grants_average_award_by_lad_by_year.csv:
          persist: true
          cache: false
