vars:
  - ROOT: ../..
  - WORKING: ../../raw/culture-landscape
  - LUME_DIR: ../../src/regional/culture-sector/pipelines
  - LUME_DATA: ../../src/regional/culture-sector/_data
  - DATA: ../../data

stages:
  stage-1:
    desc: Build longlist of organisations that appear in funding data
    cmd: papermill stage-1.ipynb | jupyter nbconvert --stdin --to markdown --output index --output-dir ${LUME_DIR}/stage-1
    deps:
      - stage-1.ipynb
      - config.py
      - ${ROOT}/raw/arts-council-investment-programme.csv
      - ${ROOT}/raw/arts-council-project-grants.csv
    outs:
      - ${ROOT}/raw/culture-landscape/funded-organisations.csv:
          persist: true
          cache: false

  stage-2:
    desc: Attempt to match companies to Companies House and Charity Commission data
    cmd: papermill stage-2.ipynb | jupyter nbconvert --stdin --to markdown --output index --output-dir ${LUME_DIR}/stage-2
    deps:
      - stage-2.ipynb
      - ${WORKING}/funded-organisations.csv
      - ${ROOT}/raw/company-data.db
    outs:
      - ${WORKING}/2-charity-match-direct.csv:
          persist: true
          cache: false
      - ${WORKING}/2-company-corrections.csv:
          persist: true
          cache: false
      - ${WORKING}/2-company-match-direct.csv:
          persist: true
          cache: false
      - ${WORKING}/2-company-match-fuzzy.csv:
          persist: true
          cache: false
      - ${WORKING}/2-sic-codes.csv:
          persist: true
          cache: false

  stage-3:
    desc: Create combined version of data from matches and SIC codes
    cmd: papermill stage-3.ipynb | jupyter nbconvert --stdin --to markdown --output index --output-dir ${LUME_DIR}/stage-3
    deps:
      - stage-3.ipynb
      - ${WORKING}/funded-organisations.csv
      - ${WORKING}/2-charity-match-direct.csv
      - ${WORKING}/2-company-corrections.csv
      - ${WORKING}/2-company-match-direct.csv
      - ${WORKING}/2-company-match-fuzzy.csv
      - ${ROOT}/raw/company-data.db
    outs:
      - ${DATA}/culture_landscape.csv:
          persist: true
          cache: false

  prepare:
    desc: Prepare the data for visualisation
    cmd: jupyter execute stage-4-prepare.ipynb
    deps:
      - ${DATA}/culture_landscape.csv
    outs:
      - ${LUME_DATA}/list.csv:
          persist: true
          cache: false
      - ${LUME_DATA}/sic_code_count.json:
          persist: true
          cache: false
      - ${LUME_DATA}/summary.json:
          persist: true
          cache: false
