name: Publish dev version

"on":
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '_config.ts'
      - 'deno.json'
      - '.github/workflows/dev-deploy.yml'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      DENO_ENV: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        run: |
          echo "DENO_DIR=$RUNNER_TEMP${{ runner.os == 'Windows' && '\\' || '/'  }}deno_cache" >> $GITHUB_ENV

      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache deno dependencies
        id: cache-deno
        uses: actions/cache@v4
        with:
          key: deno-cache-${{ hashFiles('./deno.lock') }}
          path: ${{ env.DENO_DIR }}

      - name: Deploy the site
        shell: bash
        run: deno task deploy:dev
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PATH: ${{ secrets.SSH_PATH }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSHPASS: ${{ secrets.SSHPASS }}